[package]
name = "lockdown"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5.7", features = ["derive"] }
log = "0.4.21"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
rayon = "1.10.0"
