# Build and release a new version of the package on every push to the main branch
name: Release

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      -
        name: Build
        run: cargo build --release
      -
        name: Set envvar `CARGO_VERSION` to the version from Cargo.toml
        id: set_cargo_version
        run: echo "CARGO_VERSION=$(cargo pkgid | cut -d# -f2)" >> $GITHUB_ENV
      -
        name: Create Release (Linux x86_64)
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: target/release/lockdown
          tag_name: ${{ env.CARGO_VERSION }} (Linux x86_64)
          release_name: Release